/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IReclaim {
  export type WitnessStruct = {
    addr: PromiseOrValue<string>;
    host: PromiseOrValue<string>;
  };

  export type WitnessStructOutput = [string, string] & {
    addr: string;
    host: string;
  };

  export type EpochStruct = {
    id: PromiseOrValue<BigNumberish>;
    timestampStart: PromiseOrValue<BigNumberish>;
    timestampEnd: PromiseOrValue<BigNumberish>;
    witnesses: IReclaim.WitnessStruct[];
    minimumWitnessesForClaimCreation: PromiseOrValue<BigNumberish>;
  };

  export type EpochStructOutput = [
    number,
    number,
    number,
    IReclaim.WitnessStructOutput[],
    number
  ] & {
    id: number;
    timestampStart: number;
    timestampEnd: number;
    witnesses: IReclaim.WitnessStructOutput[];
    minimumWitnessesForClaimCreation: number;
  };

  export type ProofStruct = {
    claimInfo: Claims.ClaimInfoStruct;
    signedClaim: Claims.SignedClaimStruct;
  };

  export type ProofStructOutput = [
    Claims.ClaimInfoStructOutput,
    Claims.SignedClaimStructOutput
  ] & {
    claimInfo: Claims.ClaimInfoStructOutput;
    signedClaim: Claims.SignedClaimStructOutput;
  };
}

export declare namespace Claims {
  export type ClaimInfoStruct = {
    provider: PromiseOrValue<string>;
    parameters: PromiseOrValue<string>;
    context: PromiseOrValue<string>;
  };

  export type ClaimInfoStructOutput = [string, string, string] & {
    provider: string;
    parameters: string;
    context: string;
  };

  export type CompleteClaimDataStruct = {
    identifier: PromiseOrValue<BytesLike>;
    owner: PromiseOrValue<string>;
    timestampS: PromiseOrValue<BigNumberish>;
    epoch: PromiseOrValue<BigNumberish>;
  };

  export type CompleteClaimDataStructOutput = [
    string,
    string,
    number,
    number
  ] & { identifier: string; owner: string; timestampS: number; epoch: number };

  export type SignedClaimStruct = {
    claim: Claims.CompleteClaimDataStruct;
    signatures: PromiseOrValue<BytesLike>[];
  };

  export type SignedClaimStructOutput = [
    Claims.CompleteClaimDataStructOutput,
    string[]
  ] & { claim: Claims.CompleteClaimDataStructOutput; signatures: string[] };
}

export interface IReclaimInterface extends utils.Interface {
  functions: {
    "_authorizeUpgrade(address)": FunctionFragment;
    "addNewEpoch((address,string)[],uint8)": FunctionFragment;
    "createDapp(uint256)": FunctionFragment;
    "createGroup(string,uint256)": FunctionFragment;
    "fetchEpoch(uint32)": FunctionFragment;
    "fetchWitnessesForClaim(uint32,bytes32,uint32)": FunctionFragment;
    "getContextAddressFromProof(((string,string,string),((bytes32,address,uint32,uint32),bytes[])))": FunctionFragment;
    "getContextMessageFromProof(((string,string,string),((bytes32,address,uint32,uint32),bytes[])))": FunctionFragment;
    "getMerkelizedUserParams(string,string)": FunctionFragment;
    "getProviderFromProof(((string,string,string),((bytes32,address,uint32,uint32),bytes[])))": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "merkelizeUser(((string,string,string),((bytes32,address,uint32,uint32),bytes[])),uint256)": FunctionFragment;
    "verifyMerkelIdentity(string,uint256,uint256,uint256,uint256,bytes32,uint256[8])": FunctionFragment;
    "verifyProof(((string,string,string),((bytes32,address,uint32,uint32),bytes[])))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_authorizeUpgrade"
      | "addNewEpoch"
      | "createDapp"
      | "createGroup"
      | "fetchEpoch"
      | "fetchWitnessesForClaim"
      | "getContextAddressFromProof"
      | "getContextMessageFromProof"
      | "getMerkelizedUserParams"
      | "getProviderFromProof"
      | "initialize"
      | "merkelizeUser"
      | "verifyMerkelIdentity"
      | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_authorizeUpgrade",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addNewEpoch",
    values: [IReclaim.WitnessStruct[], PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createDapp",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "createGroup",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchEpoch",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchWitnessesForClaim",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getContextAddressFromProof",
    values: [IReclaim.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getContextMessageFromProof",
    values: [IReclaim.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkelizedUserParams",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProviderFromProof",
    values: [IReclaim.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "merkelizeUser",
    values: [IReclaim.ProofStruct, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyMerkelIdentity",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [IReclaim.ProofStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "_authorizeUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addNewEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDapp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createGroup",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fetchEpoch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fetchWitnessesForClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContextAddressFromProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContextMessageFromProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkelizedUserParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProviderFromProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "merkelizeUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyMerkelIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;

  events: {
    "DappCreated(bytes32)": EventFragment;
    "EpochAdded(tuple)": EventFragment;
    "GroupCreated(uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DappCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EpochAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GroupCreated"): EventFragment;
}

export interface DappCreatedEventObject {
  dappId: string;
}
export type DappCreatedEvent = TypedEvent<[string], DappCreatedEventObject>;

export type DappCreatedEventFilter = TypedEventFilter<DappCreatedEvent>;

export interface EpochAddedEventObject {
  epoch: IReclaim.EpochStructOutput;
}
export type EpochAddedEvent = TypedEvent<
  [IReclaim.EpochStructOutput],
  EpochAddedEventObject
>;

export type EpochAddedEventFilter = TypedEventFilter<EpochAddedEvent>;

export interface GroupCreatedEventObject {
  groupId: BigNumber;
  provider: string;
}
export type GroupCreatedEvent = TypedEvent<
  [BigNumber, string],
  GroupCreatedEventObject
>;

export type GroupCreatedEventFilter = TypedEventFilter<GroupCreatedEvent>;

export interface IReclaim extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IReclaimInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _authorizeUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    addNewEpoch(
      witnesses: IReclaim.WitnessStruct[],
      requisiteWitnessesForClaimCreate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createDapp(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createGroup(
      provider: PromiseOrValue<string>,
      merkleTreeDepth: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    fetchEpoch(
      epoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IReclaim.EpochStructOutput]>;

    fetchWitnessesForClaim(
      epoch: PromiseOrValue<BigNumberish>,
      identifier: PromiseOrValue<BytesLike>,
      timestampS: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IReclaim.WitnessStructOutput[]]>;

    getContextAddressFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getContextMessageFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMerkelizedUserParams(
      provider: PromiseOrValue<string>,
      params: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getProviderFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      _semaphoreAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    merkelizeUser(
      proof: IReclaim.ProofStruct,
      _identityCommitment: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyMerkelIdentity(
      provider: PromiseOrValue<string>,
      _merkleTreeRoot: PromiseOrValue<BigNumberish>,
      _signal: PromiseOrValue<BigNumberish>,
      _nullifierHash: PromiseOrValue<BigNumberish>,
      _externalNullifier: PromiseOrValue<BigNumberish>,
      dappId: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    verifyProof(
      proof: IReclaim.ProofStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _authorizeUpgrade(
    newImplementation: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<void>;

  addNewEpoch(
    witnesses: IReclaim.WitnessStruct[],
    requisiteWitnessesForClaimCreate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createDapp(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createGroup(
    provider: PromiseOrValue<string>,
    merkleTreeDepth: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  fetchEpoch(
    epoch: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IReclaim.EpochStructOutput>;

  fetchWitnessesForClaim(
    epoch: PromiseOrValue<BigNumberish>,
    identifier: PromiseOrValue<BytesLike>,
    timestampS: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IReclaim.WitnessStructOutput[]>;

  getContextAddressFromProof(
    proof: IReclaim.ProofStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getContextMessageFromProof(
    proof: IReclaim.ProofStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getMerkelizedUserParams(
    provider: PromiseOrValue<string>,
    params: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getProviderFromProof(
    proof: IReclaim.ProofStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    _semaphoreAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  merkelizeUser(
    proof: IReclaim.ProofStruct,
    _identityCommitment: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyMerkelIdentity(
    provider: PromiseOrValue<string>,
    _merkleTreeRoot: PromiseOrValue<BigNumberish>,
    _signal: PromiseOrValue<BigNumberish>,
    _nullifierHash: PromiseOrValue<BigNumberish>,
    _externalNullifier: PromiseOrValue<BigNumberish>,
    dappId: PromiseOrValue<BytesLike>,
    _proof: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  verifyProof(
    proof: IReclaim.ProofStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _authorizeUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addNewEpoch(
      witnesses: IReclaim.WitnessStruct[],
      requisiteWitnessesForClaimCreate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createDapp(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createGroup(
      provider: PromiseOrValue<string>,
      merkleTreeDepth: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    fetchEpoch(
      epoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IReclaim.EpochStructOutput>;

    fetchWitnessesForClaim(
      epoch: PromiseOrValue<BigNumberish>,
      identifier: PromiseOrValue<BytesLike>,
      timestampS: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IReclaim.WitnessStructOutput[]>;

    getContextAddressFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getContextMessageFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getMerkelizedUserParams(
      provider: PromiseOrValue<string>,
      params: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getProviderFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      _semaphoreAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    merkelizeUser(
      proof: IReclaim.ProofStruct,
      _identityCommitment: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    verifyMerkelIdentity(
      provider: PromiseOrValue<string>,
      _merkleTreeRoot: PromiseOrValue<BigNumberish>,
      _signal: PromiseOrValue<BigNumberish>,
      _nullifierHash: PromiseOrValue<BigNumberish>,
      _externalNullifier: PromiseOrValue<BigNumberish>,
      dappId: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "DappCreated(bytes32)"(
      dappId?: PromiseOrValue<BytesLike> | null
    ): DappCreatedEventFilter;
    DappCreated(
      dappId?: PromiseOrValue<BytesLike> | null
    ): DappCreatedEventFilter;

    "EpochAdded(tuple)"(epoch?: null): EpochAddedEventFilter;
    EpochAdded(epoch?: null): EpochAddedEventFilter;

    "GroupCreated(uint256,string)"(
      groupId?: PromiseOrValue<BigNumberish> | null,
      provider?: PromiseOrValue<string> | null
    ): GroupCreatedEventFilter;
    GroupCreated(
      groupId?: PromiseOrValue<BigNumberish> | null,
      provider?: PromiseOrValue<string> | null
    ): GroupCreatedEventFilter;
  };

  estimateGas: {
    _authorizeUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addNewEpoch(
      witnesses: IReclaim.WitnessStruct[],
      requisiteWitnessesForClaimCreate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createDapp(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createGroup(
      provider: PromiseOrValue<string>,
      merkleTreeDepth: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    fetchEpoch(
      epoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fetchWitnessesForClaim(
      epoch: PromiseOrValue<BigNumberish>,
      identifier: PromiseOrValue<BytesLike>,
      timestampS: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContextAddressFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContextMessageFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMerkelizedUserParams(
      provider: PromiseOrValue<string>,
      params: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProviderFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _semaphoreAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    merkelizeUser(
      proof: IReclaim.ProofStruct,
      _identityCommitment: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyMerkelIdentity(
      provider: PromiseOrValue<string>,
      _merkleTreeRoot: PromiseOrValue<BigNumberish>,
      _signal: PromiseOrValue<BigNumberish>,
      _nullifierHash: PromiseOrValue<BigNumberish>,
      _externalNullifier: PromiseOrValue<BigNumberish>,
      dappId: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    verifyProof(
      proof: IReclaim.ProofStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _authorizeUpgrade(
      newImplementation: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addNewEpoch(
      witnesses: IReclaim.WitnessStruct[],
      requisiteWitnessesForClaimCreate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createDapp(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createGroup(
      provider: PromiseOrValue<string>,
      merkleTreeDepth: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    fetchEpoch(
      epoch: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fetchWitnessesForClaim(
      epoch: PromiseOrValue<BigNumberish>,
      identifier: PromiseOrValue<BytesLike>,
      timestampS: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContextAddressFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContextMessageFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMerkelizedUserParams(
      provider: PromiseOrValue<string>,
      params: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProviderFromProof(
      proof: IReclaim.ProofStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _semaphoreAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    merkelizeUser(
      proof: IReclaim.ProofStruct,
      _identityCommitment: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyMerkelIdentity(
      provider: PromiseOrValue<string>,
      _merkleTreeRoot: PromiseOrValue<BigNumberish>,
      _signal: PromiseOrValue<BigNumberish>,
      _nullifierHash: PromiseOrValue<BigNumberish>,
      _externalNullifier: PromiseOrValue<BigNumberish>,
      dappId: PromiseOrValue<BytesLike>,
      _proof: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    verifyProof(
      proof: IReclaim.ProofStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
